# Write an infinite generator of fibonacci numbers, with optional start values
def fibonacci(a=0, b=1):
    """Fibonacci numbers generator"""
    pass


# Write a generator of all permutations of a sequence
def permutations(items):
    pass


# Use this to write a generator of all permutations of a word
def w_perm(w):
    pass


# Use the Fibonacci generator to create another one that only generates fib numbers with a given factor
def fib_div(d):
    pass

# Alternatively, write a generator expression that achieves the same result


# Write generator that puts a user-specified limit on the number of items generated by any given generator
def first(n, g):
    pass

# Again, you could also write a generator expression that achieves the same result

if __name__ == "__main__":

    print(*permutations(['r', 'e', 'd']))
    print(*w_perm('game'))

    #etc.
